Repository lasseborly/forbidden-sheets, pull requests merged in 2020-10, with the labels that each got.

#1 Initial translations setup
  translations/cs.json
  translations/en.json
Labels: enhancement

#2 Update image path.
  README.md
Labels: bug

#3 Add link to readme.
  README.md
Labels: documentation

#4 Translations update from Weblate
  translations/da.json
  translations/de.json
  translations/sv.json
Labels: translation
